Repository EduardoScarante/vitrine-4net, pull requests merged in 2023-07, with the labels that each got.

#3 Estilização do card de itens da vitrine
  src/modules/dash/components/itemBox.vue
Labels: documentation

#4 add imagens - storage
  src/modules/dash/api.js
  src/modules/dash/api/index.js
  src/modules/dash/store/index.js
  src/modules/dash/views/Create.vue
  src/modules/dash/views/Home.vue
Labels: enhancement

#7 Cria um componente de loading para a home
  src/modules/dash/components/loader.vue
  src/modules/dash/views/Home.vue
Labels: enhancement

#6 feat/update & delete itens
  src/modules/dash/api/index.js
  src/modules/dash/components/detailModal.vue
  src/modules/dash/components/itemBox.vue
  src/modules/dash/store/index.js
  src/modules/dash/views/Create.vue
  src/modules/dash/views/Home.vue
Labels: enhancement

#8 fix/side bar
  src/assets/bg.png
  src/modules/dash/components/detailModal.vue
  src/modules/dash/store/index.js
  src/modules/dash/views/Home.vue
Labels: enhancement

#12 estilizacao do btn de logout
  src/modules/dash/views/Home.vue
Labels: documentation

#13 Add/modal create
  src/App.vue
  src/assets/logo-branca-4net.png
  src/modules/dash/api/index.js
  src/modules/dash/components/createItem.vue
  src/modules/dash/router/index.js
  src/modules/dash/store/index.js
  src/modules/dash/views/Create.vue
  src/modules/dash/views/Edit.vue
  src/modules/dash/views/Home.vue
Labels: enhancement

#14 Merge all and fix pr's problems
  src/modules/auth/api.js
  src/modules/auth/components/Login.vue
  src/modules/auth/components/Register.vue
  src/modules/auth/store/index.js
  src/modules/dash/api/index.js
  src/modules/dash/views/Home.vue
Labels: enhancement

#15 Fix/style
  src/modules/dash/components/Confirmation.vue
  src/modules/dash/components/createItem.vue
  src/modules/dash/components/detailModal.vue
  src/modules/dash/components/itemBox.vue
  src/modules/dash/components/loader.vue
  src/modules/dash/store/index.js
  src/modules/dash/views/Home.vue
Labels: enhancement

#18 feat/edit image
  firebase.config.js
  index.html
  src/modules/auth/api.js
  src/modules/auth/components/Login.vue
  src/modules/auth/components/Register.vue
  src/modules/auth/store/index.js
  src/modules/auth/view/Access.vue
  src/modules/dash/api/index.js
  src/modules/dash/components/Confirmation.vue
  src/modules/dash/components/Error.vue
  src/modules/dash/components/createItem.vue
  src/modules/dash/components/detailModal.vue
  src/modules/dash/components/itemBox.vue
  src/modules/dash/components/loader.vue
  src/modules/dash/store/index.js
  src/modules/dash/views/Home.vue
  src/styles/settings.scss
  src/views/Home.vue
Labels: enhancement

#19 Alerts
  src/modules/auth/api.js
  src/modules/auth/components/Login.vue
  src/modules/auth/components/Register.vue
  src/modules/auth/store/index.js
  src/modules/dash/store/index.js
  src/modules/dash/views/Home.vue
Labels: documentation

#21 Arruma o botão do toggle do login
  src/modules/auth/components/Login.vue
Labels: bug

#22 Alterações de estilo
  src/modules/dash/components/detailModal.vue
  src/modules/dash/views/Home.vue
Labels: bug
